server:
  port: 19094  # ✅ 두 번째 인스턴스의 고정 포트

spring:
  application:
    name: product-service

eureka:
  instance:
    instance-id: product-service-19094  # ✅ 개별 인스턴스 ID
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
