server:
  port: 19090

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:19090/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
