server:
  port: 0  # ✅ 개별 서비스가 자동으로 포트 지정

spring:
  application:
    name: config  # ✅ Config 서버명
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chaewKim/msa-config-repo  # ✅ GitHub의 msa-config-repo 주소
          search-paths: config/  # ✅ 설정 파일이 있는 경로 (여기가 중요!)
          default-label: main  # ✅ GitHub 브랜치 (필요 시 변경)
          clone-on-start: true  # ✅ 서버 시작 시 GitHub에서 설정 가져오도록 설정