server:
  port: 19090  # ✅ Eureka 서버의 포트

spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8888
      profile: default

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
