server:
  port: 19091  # ✅ Gateway 포트

spring:
  application:
    name: gateway  # ✅ 서비스 이름
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # ✅ Eureka 기반 자동 라우팅 활성화
          lower-case-service-id: true  # ✅ 서비스 ID 소문자로 변환
      routes:
        - id: product-service
          uri: lb://product-service  # ✅ Eureka에서 'product-service'로 등록된 서비스로 요청을 전달
          predicates:
            - Path=/product/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # ✅ Eureka 서버 주소
    register-with-eureka: true  # ✅ Eureka에 Gateway 등록
    fetch-registry: true  # ✅ Eureka에서 서비스 목록 가져오기
