server:
  port: 19095

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_db
    username: admin
    password: adminpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
